repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.13"
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --output-format, concise]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/kschweiger/pre-commit-hooks
    rev: a34afbe181aa96a616bb17e6ede65e079d5d198d
    hooks:
      - id: comment-keywords
